[tool.poetry]
name = "car_tracking"
version = "0.1.0"
description = ""
authors = ["palandr1234"]
readme = "README.md"
packages = [{include = "car_tracking"}]

[tool.poetry.dependencies]
python = ">=3.9"
numpy = "^1.25.0"
torch = "<2.0.0"
opencv-python = ">=4.1.1"
